name: tf2
channels:
  - anaconda
  - bokeh
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astroid=2.14.2
  - async-lru=2.0.4
  - atomicwrites=1.4.0
  - autopep8=1.6.0
  - babel=2.11.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.2
  - binaryornot=0.4.4
  - black=23.11.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - chardet=4.0.0
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.2.0
  - cookiecutter=2.5.0
  - cryptography=41.0.7
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - cycler=0.12.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.7
  - docstring-to-markdown=0.11
  - entrypoints=0.4
  - flake8=6.0.0
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.78.3
  - glib-tools=2.78.3
  - gst-plugins-base=1.22.8
  - gstreamer=1.22.8
  - icu=73.2
  - imagesize=1.4.1
  - importlib-metadata=7.0.0
  - importlib-resources=6.1.1
  - importlib_metadata=7.0.0
  - importlib_resources=6.1.1
  - inflection=0.5.1
  - intel-openmp=2023.2.0
  - intervaltree=3.1.0
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jaraco.classes=3.2.1
  - jellyfish=1.0.1
  - jinja2=3.1.2
  - json5=0.9.6
  - jupyter-lsp=2.2.0
  - jupyter_client=7.4.9
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - keyring=23.13.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=15.0.7
  - libdeflate=1.19
  - libffi=3.4.2
  - libglib=2.78.3
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libogg=1.3.4
  - libpng=1.6.39
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libsqlite=3.44.2
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.6
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mkl=2023.2.0
  - more-itertools=10.1.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nbformat=5.9.2
  - notebook-shim=0.2.3
  - numpydoc=1.5.0
  - openjpeg=2.5.0
  - openssl=3.2.0
  - overrides=7.4.0
  - pandocfilters=1.5.0
  - paramiko=2.8.1
  - parso=0.8.3
  - pathspec=0.10.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - pluggy=1.0.0
  - ply=3.11
  - prometheus_client=0.14.1
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.0.1
  - pylint=2.16.2
  - pylint-venv=2.3.0
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyqtwebengine=5.15.9
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-lsp-black=1.2.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.7.2
  - python-slugify=5.0.2
  - python_abi=3.9
  - pytoolconfig=1.2.6
  - pytz=2023.3.post1
  - pywin32-ctypes=0.2.0
  - pywinpty=2.0.10
  - pyyaml=6.0.1
  - qdarkstyle=3.0.2
  - qstylizer=0.2.2
  - qt-main=5.15.8
  - qt-webengine=5.15.9
  - qtawesome=1.2.2
  - qtpy=2.4.1
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.3.5
  - rope=1.7.0
  - rtree=1.0.1
  - send2trash=1.8.2
  - setuptools=68.0.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.4.3
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.11.0
  - terminado=0.17.1
  - text-unidecode=1.3
  - textdistance=4.2.1
  - three-merge=0.1.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - typing_extensions=4.7.1
  - ucrt=10.0.20348.0
  - ujson=5.4.0
  - unicodedata2=15.1.0
  - unidecode=1.2.0
  - vc=14.2
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - watchdog=2.1.6
  - websocket-client=0.58.0
  - whatthepatch=1.0.2
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zipp=3.17.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - alembic==1.13.1
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-generator==1.10
      - attrs==23.2.0
      - bibtexparser==1.4.1
      - bleach==6.1.0
      - cachetools==5.3.2
      - certipy==0.1.3
      - charset-normalizer==3.3.2
      - cloudpickle==3.0.0
      - comm==0.2.1
      - debugpy==1.8.0
      - docutils==0.20.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - flatbuffers==23.5.26
      - fonttools==4.46.0
      - fqdn==1.5.1
      - gast==0.4.0
      - google-auth==2.25.1
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - greenlet==3.0.3
      - grpcio==1.59.3
      - h5py==3.10.0
      - idna==3.6
      - ipykernel==6.27.1
      - ipypublish==0.10.12
      - ipython==8.18.1
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - joblib==1.3.2
      - jsonextended==0.7.11
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-telemetry==0.1.0
      - jupyterhub==4.0.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.9
      - jupytext==1.16.0
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - keras-tuner==1.4.6
      - kt-legacy==1.0.5
      - libclang==16.0.6
      - mako==1.3.0
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - nbclient==0.5.13
      - nbconvert==7.14.0
      - nest-asyncio==1.5.8
      - notebook==7.0.6
      - numpy==1.26.2
      - oauthlib==3.2.2
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - ordered-set==4.1.0
      - packaging==23.2
      - pandas==2.1.4
      - panflute==2.3.0
      - pathlib2==2.3.7.post1
      - pillow==10.1.0
      - platformdirs==4.1.0
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.41
      - protobuf==3.19.6
      - psutil==5.9.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pygments==2.17.2
      - pyopenssl==23.3.0
      - pywin32==306
      - pyzmq==25.1.2
      - qtconsole==5.5.1
      - referencing==0.32.1
      - requests-oauthlib==1.3.1
      - rpds-py==0.16.2
      - rsa==4.9
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - spyder-kernels==1.10.0
      - sqlalchemy==2.0.25
      - stack-data==0.6.3
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - testpath==0.6.0
      - threadpoolctl==3.2.0
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.0
      - types-python-dateutil==2.8.19.20240106
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.1.0
      - wcwidth==0.2.12
      - webcolors==1.13
      - webencodings==0.5.1
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - wrapt==1.16.0
